image: rocker/tidyverse

stages:
  - build

building:
  stage: build
  script:
    - > # Install GLPK library necessary for qgraph package in R
      apt-get update && 
      apt-get install -y
      libglpk-dev
      libglu1-mesa-dev
      freeglut3-dev
      mesa-common-dev 
    - R -e "remotes::install_deps(dependencies = TRUE)"
    - R -e 'devtools::check()'
  only:
    refs:
      - master
